#ifndef	SKYRIMSOULSRE_VERSION_INCLUDED
#define SKYRIMSOULSRE_VERSION_INCLUDED

#define SKYRIMSOULSRE_VERSION_MAJOR		1
#define SKYRIMSOULSRE_VERSION_MINOR		0
#define SKYRIMSOULSRE_VERSION_PATCH		3
#define SKYRIMSOULSRE_VERSION_BETA		0
#define SKYRIMSOULSRE_VERSION_VERSTRING	"1, 0, 3, 0"

#endif
