#ifndef	SKYRIMSOULSRE_VERSION_INCLUDED
#define SKYRIMSOULSRE_VERSION_INCLUDED

#define SKYRIMSOULSRE_MAKE_STR_HELPER(x) #x
#define SKYRIMSOULSRE_MAKE_STR(x) SKYRIMSOULSRE_MAKE_STR_HELPER(x)

#define SKYRIMSOULSRE_VERSION_MAJOR		1
#define SKYRIMSOULSRE_VERSION_MINOR		0
#define SKYRIMSOULSRE_VERSION_PATCH		5
#define SKYRIMSOULSRE_VERSION_BETA		0
#define SKYRIMSOULSRE_VERSION_VERSTRING	SKYRIMSOULSRE_MAKE_STR(SKYRIMSOULSRE_VERSION_MAJOR) "." SKYRIMSOULSRE_MAKE_STR(SKYRIMSOULSRE_VERSION_MINOR) "." SKYRIMSOULSRE_MAKE_STR(SKYRIMSOULSRE_VERSION_PATCH) "." SKYRIMSOULSRE_MAKE_STR(SKYRIMSOULSRE_VERSION_BETA)

#endif
