set(SOURCES
	include/AudioHooks.h
	include/AutoCloseManager.h
	include/Controls/BSWin32KeyboardDeviceEx.h
	include/Controls/CameraMovement.h
	include/Controls/InputHandlerEx.h
	include/Controls/MapInputHandlerEx.h
	include/Controls/MenuControlsEx.h
	include/Controls/PlayerControlsEx.h
	include/EngineFixesChecker.h
	include/ItemMenuUpdater.h
	include/MenuCache.h
	include/MenuProcessing.h
	include/Menus/BarterMenuEx.h
	include/Menus/BookMenuEx.h
	include/Menus/CombatAlertOverlayMenu.h
	include/Menus/ConsoleEx.h
	include/Menus/ContainerMenuEx.h
	include/Menus/CustomMenuEx.h
	include/Menus/DialogueMenuEx.h
	include/Menus/FavoritesMenuEx.h
	include/Menus/GiftMenuEx.h
	include/Menus/HUDMenuEx.h
	include/Menus/InventoryMenuEx.h
	include/Menus/JournalMenuEx.h
	include/Menus/LevelUpMenuEx.h
	include/Menus/LockpickingMenuEx.h
	include/Menus/MagicMenuEx.h
	include/Menus/MapMenuEx.h
	include/Menus/MessageBoxMenuEx.h
	include/Menus/ModManagerMenuEx.h
	include/Menus/SleepWaitMenuEx.h
	include/Menus/StatsMenuEx.h
	include/Menus/TrainingMenuEx.h
	include/Menus/TutorialMenuEx.h
	include/Menus/TweenMenuEx.h
	include/Offsets.h
	include/PCH.h
	include/PapyrusHook.h
	include/Settings.h
	include/SkyrimSoulsRE.h
	include/SlowMotionHandler.h
	include/UIBlurManagerEx.h
	include/Util.h
	src/AudioHooks.cpp
	src/AutoCloseManager.cpp
	src/Controls/BSWin32KeyboardDeviceEx.cpp
	src/Controls/CameraMovement.cpp
	src/Controls/MenuControlsEx.cpp
	src/Controls/PlayerControlsEx.cpp
	src/ItemMenuUpdater.cpp
	src/MenuCache.cpp
	src/MenuProcessing.cpp
	src/Menus/BarterMenuEx.cpp
	src/Menus/BookMenuEx.cpp
	src/Menus/CombatAlertOverlayMenu.cpp
	src/Menus/ConsoleEx.cpp
	src/Menus/ContainerMenuEx.cpp
	src/Menus/CustomMenuEx.cpp
	src/Menus/DialogueMenuEx.cpp
	src/Menus/FavoritesMenuEx.cpp
	src/Menus/GiftMenuEx.cpp
	src/Menus/HUDMenuEx.cpp
	src/Menus/InventoryMenuEx.cpp
	src/Menus/JournalMenuEx.cpp
	src/Menus/LevelUpMenuEx.cpp
	src/Menus/LockpickingMenuEx.cpp
	src/Menus/MagicMenuEx.cpp
	src/Menus/MapMenuEx.cpp
	src/Menus/MessageBoxMenuEx.cpp
	src/Menus/ModManagerMenuEx.cpp
	src/Menus/SleepWaitMenuEx.cpp
	src/Menus/StatsMenuEx.cpp
	src/Menus/TrainingMenuEx.cpp
	src/Menus/TutorialMenuEx.cpp
	src/Menus/TweenMenuEx.cpp
	src/PCH.cpp
	src/PapyrusHook.cpp
	src/Settings.cpp
	src/SkyrimSoulsRE.cpp
	src/SlowMotionHandler.cpp
	src/UIBlurManagerEx.cpp
	src/main.cpp
	src/Util.cpp
)
